spring:
  application:
    name: ag-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yb7553/ag-parent.git
          username: 23218371@qq.com
          password: yb718293
          basedir: D:\basedir
  rabbitmq:
    host: 106.12.151.12
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8750
management:
  endpoints:
    web:
      exposure:
        include: "*"

