spring:
  application:
    name: ag-gate

zuul:
  prefix: /api
  routes:
    user-center:
      path: /uc/**
      serviceId: user-center

eureka:
  client:
    service-url:
      defaultZone: http://qoocar:qoocar@localhost:8761/eureka

server:
  port: 8765